export type Testimonial = { quote: string; name: string; role: string };

export const testimonials: Testimonial[] = [
  { quote: "Clients don't shop for mortgages during business hours only. Before Mercury Call Desk, I'd miss late-night calls and lose those leads to bigger firms. Now, every call gets answered, prequalification questions are asked, and serious clients are routed to me first thing in the morning. I've picked up three deals in the last month that I know I would have lost otherwise.", name: "Rebecca Collins", role: "Mortgage Broker" },
  { quote: "We were constantly fielding calls about prescription refills and pickup times. It tied up our staff, and patients got frustrated waiting. With Mercury Call Desk, callers can request refills, get hours, and even check order status automatically. Our pharmacists stay focused on care, and patients love the faster service.", name: "James O'Malley, COO", role: "Regional Pharmacy Chain" },
  { quote: "Leads are everything in our business, but missed calls meant wasted marketing spend. Mercury Call Desk answers instantly, qualifies prospects, and sets up callbacks. We've doubled our conversion rate from inbound calls because now every single one gets captured.", name: "Angela Wright", role: "Director of Client Services" },
  { quote: "We were missing after-hours calls for breakdowns, and those customers just went to the next shop. Mercury Call Desk now takes those calls, books the repair slot, and even sends directions by text. We're winning business we used to lose without lifting a finger.", name: "Tom Harris", role: "Auto Repair Shop Owner" },
  { quote: "Clients expect us to be available 24/7 when something breaks. Mercury Call Desk takes those emergency calls, gathers details, and escalates critical issues directly to the right tech. We haven't missed an urgent ticket since.", name: "Nina Patel, COO", role: "IT Services Firm" },
  { quote: "Tenants call at all hours with maintenance issues. Before, those went to voicemail, and complaints piled up. Now, Mercury Call Desk logs the issue, dispatches the right contractor, and keeps tenants updated. It's professionalized our entire operation.", name: "Marcus Green", role: "Property Manager" },
  { quote: "Having a single phone line and only one server available to answer it was killing us on Friday nights. Customers kept saying they could never get through to place an order. Since adding Mercury Call Desk, those calls actually get answered, and I only need to capture one or two of those orders to cover the cost for the whole month.", name: "Carlos Mendez", role: "Restaurant Owner" },
  { quote: "Patients hated getting voicemail when calling after hours. They'd tell us they felt like their concerns weren't important. Now, Mercury Call Desk schedules appointments, leaves reminders, and even handles reschedules automatically. It's like having an extra receptionist who never sleeps.", name: "Dr. Priya Nair", role: "Family Medicine Clinic" },
  { quote: "When I'm with clients, I can't afford to stop and answer every call, but missing them meant missing deals. With Mercury Call Desk, calls are qualified, leads are captured, and the serious buyers get to me fast. I've closed three new clients in the last two months thanks to calls I would have missed before.", name: "Mike Stevens", role: "Real Estate Broker" },
  { quote: "In the summer we're slammed, and customers won't wait on hold. Before Mercury Call Desk, we lost work because people just hung up and called the next company. Now, every call gets picked up, appointments are booked, and my crew stays focused on the job instead of the phone.", name: "Lisa Thompson", role: "HVAC Business Owner" },
  { quote: "We can't have a missed call from a potential client—it's too costly. Mercury Call Desk takes detailed intake information, qualifies the case, and books consultations directly into our calendar. Clients feel like they're speaking to a real assistant, and we don't lose valuable leads anymore.", name: "David Le", role: "Law Firm Founder & Partner" },
  { quote: "Our customers constantly asked about order status. My team spent hours just tracking shipments. Now Mercury Call Desk handles those calls automatically—it verifies the order number and gives tracking updates instantly. It freed my team to focus on growing the business instead of answering the same question 100 times a week.", name: "Emily Johnson", role: "E-Commerce Manager" },
];
